### ISSUE TITLE
Duplicate of mastadon and others

### ISSUE THREAD

**Issue by ghostdevv** [AlexFF000/federnet#2] opened 2022-11-09 22:57 UTC
Title says it all smh

**Comment by AlexFF000** [comment] 2022-11-10 12:26
Closing as its not a duplicate of "mast**a**don", ~~it is a duplicate of "mast**o**don"~~ it is it's own unique project with its own advantages.  Learn to spell smh.

**Closed as completed by AlexFF000** 2022-11-10 12:26 UTC
